### PR TITLE
ADMINUI-1584 Need to be able to run Analytics for a specific Server o…

### PR DESCRIPTION
**Pull request by dan-luk**
…r Zone via AdminUI

### CODE REVIEW

**Comment by lloydde** [comment]
I'm going to close this pull request for now as I circle back with support on this.

**Comment by dan-luk** [comment]
closing usually means problem with the code or "do not want this"
please advice

**Comment by lloydde** [comment]
Fair enough. Will tag it instead.

**Comment by bahamat** [comment]
Cloud analytics has been removed from Triton.

**Pull request closed without merging**
